
export const categoryConstants={
    
    GET_CATEGORY_REQUEST:'GET_CATEGORY_REQUEST',
    GET_CATEGORY_FAILED:'GET_CATEGORY_FAILED',
    GET_CATEGORY_SUCCESS:'GET_CATEGORY_SUCCESS',
    GET_MOVIE_REQUEST:'GET_MOVIE_REQUEST',
    GET_MOVIE_FAILED:'GET_MOVIE_FAILED',
    GET_MOVIE_SUCCESS:'GET_MOVIE_SUCCESS',
   
}
